

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    mem_limit: 1g
    cpu_shares: 1024

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_SMTP_ENABLED=true
    - GF_SMTP_HOST=smtp.gmail.com:587
    - GF_SMTP_USER=devinkondeti@gmail.com
    - GF_SMTP_PASSWORD= ervb oerd wuty ihnc
    - GF_SMTP_FROM_ADDRESS=devinkondeti@gmail.com
    - GF_SMTP_FROM_NAME=Grafana Alerts
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
